package com.example.tolovepy.everywheretrip.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.tolovepy.everywheretrip.bean.BanmiBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BANMI_BEAN".
*/
public class BanmiBeanDao extends AbstractDao<BanmiBean, Long> {

    public static final String TABLENAME = "BANMI_BEAN";

    /**
     * Properties of entity BanmiBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Lid = new Property(0, Long.class, "lid", true, "_id");
        public final static Property Id = new Property(1, int.class, "id", false, "ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Location = new Property(3, String.class, "location", false, "LOCATION");
        public final static Property Occupation = new Property(4, String.class, "occupation", false, "OCCUPATION");
        public final static Property Introduction = new Property(5, String.class, "introduction", false, "INTRODUCTION");
        public final static Property Following = new Property(6, int.class, "following", false, "FOLLOWING");
        public final static Property Photo = new Property(7, String.class, "photo", false, "PHOTO");
        public final static Property IsFollowed = new Property(8, boolean.class, "isFollowed", false, "IS_FOLLOWED");
    }


    public BanmiBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BanmiBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BANMI_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: lid
                "\"ID\" INTEGER NOT NULL ," + // 1: id
                "\"NAME\" TEXT," + // 2: name
                "\"LOCATION\" TEXT," + // 3: location
                "\"OCCUPATION\" TEXT," + // 4: occupation
                "\"INTRODUCTION\" TEXT," + // 5: introduction
                "\"FOLLOWING\" INTEGER NOT NULL ," + // 6: following
                "\"PHOTO\" TEXT," + // 7: photo
                "\"IS_FOLLOWED\" INTEGER NOT NULL );"); // 8: isFollowed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BANMI_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BanmiBean entity) {
        stmt.clearBindings();
 
        Long lid = entity.getLid();
        if (lid != null) {
            stmt.bindLong(1, lid);
        }
        stmt.bindLong(2, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(4, location);
        }
 
        String occupation = entity.getOccupation();
        if (occupation != null) {
            stmt.bindString(5, occupation);
        }
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(6, introduction);
        }
        stmt.bindLong(7, entity.getFollowing());
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(8, photo);
        }
        stmt.bindLong(9, entity.getIsFollowed() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BanmiBean entity) {
        stmt.clearBindings();
 
        Long lid = entity.getLid();
        if (lid != null) {
            stmt.bindLong(1, lid);
        }
        stmt.bindLong(2, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(4, location);
        }
 
        String occupation = entity.getOccupation();
        if (occupation != null) {
            stmt.bindString(5, occupation);
        }
 
        String introduction = entity.getIntroduction();
        if (introduction != null) {
            stmt.bindString(6, introduction);
        }
        stmt.bindLong(7, entity.getFollowing());
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(8, photo);
        }
        stmt.bindLong(9, entity.getIsFollowed() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BanmiBean readEntity(Cursor cursor, int offset) {
        BanmiBean entity = new BanmiBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // lid
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // location
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // occupation
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // introduction
            cursor.getInt(offset + 6), // following
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // photo
            cursor.getShort(offset + 8) != 0 // isFollowed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BanmiBean entity, int offset) {
        entity.setLid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLocation(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOccupation(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIntroduction(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFollowing(cursor.getInt(offset + 6));
        entity.setPhoto(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsFollowed(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BanmiBean entity, long rowId) {
        entity.setLid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BanmiBean entity) {
        if(entity != null) {
            return entity.getLid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BanmiBean entity) {
        return entity.getLid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
