package com.example.tolovepy.everywheretrip.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tolovepy.everywheretrip.bean.BanmiBean;

import com.example.tolovepy.everywheretrip.dao.BanmiBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig banmiBeanDaoConfig;

    private final BanmiBeanDao banmiBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        banmiBeanDaoConfig = daoConfigMap.get(BanmiBeanDao.class).clone();
        banmiBeanDaoConfig.initIdentityScope(type);

        banmiBeanDao = new BanmiBeanDao(banmiBeanDaoConfig, this);

        registerDao(BanmiBean.class, banmiBeanDao);
    }
    
    public void clear() {
        banmiBeanDaoConfig.clearIdentityScope();
    }

    public BanmiBeanDao getBanmiBeanDao() {
        return banmiBeanDao;
    }

}
